### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by bjsi** [browneyedsoul/RemNote-RunJS#1]
- It seems to re-run the code every time you change the text, rather than waiting until you press the play button. Is that intended?
- I'm curious what this is for?
https://github.com/browneyedsoul/RemNote-RunJS/blob/636ddf241d918152d059b2c5fd21f1af39aaebdf/src/widgets/index.tsx#L53C1-L56

**Comment by browneyedsoul** [comment]
①  Yes, I intended to use it to track the latest state before pressing the button. I'm hoping to find a more convenient way to do this without the procedure, but for now it seems necessary. 

②  Without the codes, the code block cannot be properly created due to delimiter issues in RemNote that may differ from other editors. 

Thank you for the review! Please let me know if any changes need to be made to the codes :)

**Comment by bjsi** [comment]
ok sounds good, I approved it :)

**Comment by browneyedsoul** [comment]
Thx James! 😄
